"""add_session_expiry_fields

Revision ID: 9403029f294b
Revises: b9fcb47d62ac
Create Date: 2026-02-08 13:02:39.329125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9403029f294b'
down_revision: Union[str, Sequence[str], None] = 'b9fcb47d62ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable first
    op.add_column('chat_sessions', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('chat_sessions', sa.Column('expires_at', sa.DateTime(), nullable=True))
    
    # 2. Populate existing rows with current time for last_activity_at
    op.execute("UPDATE chat_sessions SET last_activity_at = CURRENT_TIMESTAMP WHERE last_activity_at IS NULL")
    
    # 3. Make last_activity_at not null
    with op.batch_alter_table('chat_sessions') as batch_op:
        batch_op.alter_column('last_activity_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'expires_at')
    op.drop_column('chat_sessions', 'last_activity_at')
    # ### end Alembic commands ###
