"""add_city_to_users_and_context_to_sessions

Revision ID: b9fcb47d62ac
Revises: cc4ef454de9d
Create Date: 2026-02-08 10:57:15.865410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9fcb47d62ac'
down_revision: Union[str, Sequence[str], None] = 'cc4ef454de9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_name', sa.String(length=100), nullable=True))
    op.add_column('chat_sessions', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    op.drop_column('chat_sessions', 'location')
    op.drop_column('chat_sessions', 'user_name')
    # ### end Alembic commands ###
